### PR TITLE
Add style.less file

### PR DESCRIPTION
**Pull request by ocefpaf**
This is the `style.less` file used to make `style.css` via `lessc -x style.less ../css/style.css`.

It requereis `bootstrap` but I am working on removing that dependency.

### CODE REVIEW

**Comment by mwengren** [comment]
@ocefpaf, could the less rules be converted to sass/scss and embedded alongside the existing individual .scss files in https://github.com/ioos/ioos_jekyll_theme/tree/gh-pages/_sass?  Then imported in here: https://github.com/ioos/ioos_jekyll_theme/blob/gh-pages/assets/css/main.scss?  That way it could all be bundled in a single resulting CSS file and would be much simpler.

I don't know how transferable the syntax/functionality is tho...

**Comment by ocefpaf** [comment]
> @ocefpaf, could the less rules be converted to sass/scss and embedded alongside the existing individual .scss files in https://github.com/ioos/ioos_jekyll_theme/tree/gh-pages/_sass?  Then imported in here: https://github.com/ioos/ioos_jekyll_theme/blob/gh-pages/assets/css/main.scss?

Probably.

> I don't know how transferable the syntax/functionality is tho...

Neither do I. These web technologies are all new to me.

**Comment by mwengren** [comment]
Ok, if I have some time I may try to research if you don't get to it first
(next week probably).  Does Jekyll/GitHub compile the less file as well and
produce CSS?  If so then may not need to bother.  Learning myself a lot of
this...

**Comment by ocefpaf** [comment]
> Does Jekyll/GitHub compile the less file as well and
> produce CSS? 

I am compiling it manually. Not sure if that is possible.

**Comment by ocefpaf** [comment]
> Ok, if I have some time I may try to research if you don't get to it first
> (next week probably).

@mwengren I am testing things locally and I believe I got it. So do not waste your time with this right now. (Wait until I crash-and-burn-and-cry-for-help :smile:)

**Pull request merged**
