### PR TITLE
Add link to the rendered version

### PR DESCRIPTION
**Pull request by ocefpaf**
Adding a link to the rendered version of the theme at https://ioos.github.io/ioos_jekyll_theme

### CODE REVIEW

**Comment by mwengren** [comment]
Strange that it didn't build... there should be a green check after the
last commit that the build was successful.  Site looks blank currently:
https://github.com/ioos/ioos_jekyll_theme/commits/gh_pages

Micah

**Comment by ocefpaf** [comment]
Noticed that too. I will look into it tomorrow.

**Comment by mwengren** [comment]
@ocepaf I think I discovered the issue.  Branch name must be 'gh-pages' in
order for the link in the readme to work.  Currently it is 'gh_pages':
https://github.com/ioos/ioos_jekyll_theme/tree/gh_pages.

I am going to push some style changes @lukecampbell suggested shortly as
well..

**Comment by ocefpaf** [comment]
Classical `-` vs `_` error :smile: 

Thanks for fixing it.

**Comment by mwengren** [comment]
Ok, I just pushed a 'gh-pages' branch to test that site works as expected,
but I'll let you handle the branch management @ocefpaf if you want to just
copy master to gh-pages to keep in sync.  I deleted my gh-pages branch. See
PR #8

**Comment by ocefpaf** [comment]
I was thinking about removing master and making `gh-pages` the default branch. What do you think? I usually do that for page only repos.

**Comment by mwengren** [comment]
I guess that would simplify it.  +1.  I did that for the Catalog repo
originally but went back to master, only because there was non-Github pages
content we wanted to add to the repo and it was nice to be able to hide all
of the extra stuff.  But since this is only about the template I think it
makes sense.

**Comment by ocefpaf** [comment]
Alright. Merged #8, updated `gh-pages`, and removed `master`. We should be all set now.

**Pull request merged**
